# NOSP Cargo Build Configuration
# This file is used by cargo to configure build settings

[build]
# Target Windows x86_64 by default
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
# Use the MSVC linker
linker = "link.exe"
